on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deno_ci:
    uses: cross-org/workflows/.github/workflows/deno-ci.yml@main
    with:
      entrypoint: mod.ts
  bun_ci:
    uses: cross-org/workflows/.github/workflows/bun-ci.yml@main
    with:
      jsr_dependencies: "@cross/test @std/assert @cross/utils @std/encoding @std/io @std/media-types @std/path"
  node_ci:
    uses: cross-org/workflows/.github/workflows/node-ci.yml@main
    with:
      jsr_dependencies: "@cross/test @std/assert @cross/utils @std/encoding @std/io @std/media-types @std/path"
      test_target: "utils/*.test.ts"